# Dependabot will run on day 20 of each month at 03:58 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 2
      timezone: "Europe/Berlin"
      cronjob: "58 3 20 * *"
    open-pull-requests-limit: 15
    assignees:
      - "OlliMartin"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 2
      timezone: "Europe/Berlin"
      cronjob: "58 3 20 * *"
    open-pull-requests-limit: 15
    assignees:
      - "OlliMartin"
